import { User, Project } from "@/types";

export const mockUsers: User[] = [
  { id: "1", email: "admin@example.com", name: "Admin User", role: "admin" },
  { id: "2", email: "pm@example.com", name: "Sarah Manager", role: "project_manager" },
  { id: "3", email: "dev@example.com", name: "John Developer", role: "developer" },
  { id: "4", email: "dev2@example.com", name: "Jane Developer", role: "developer" },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "E-Commerce Platform",
    description: "Building a modern e-commerce platform with React and Node.js",
    status: "in_progress",
    priority: "high",
    start_date: "2024-01-15",
    end_date: "2024-06-30",
    progress: 65,
    budget: 150000,
    spent_budget: 87500,
    project_manager_id: "2",
    manager_name: "Sarah Manager",
    team_members: ["3", "4"],
    created_at: "2024-01-10",
    updated_at: "2024-03-15",
    created_by: "1",
  },
  {
    id: "p2",
    name: "Mobile App Redesign",
    description: "Complete UI/UX overhaul of the mobile application",
    status: "in_progress",
    priority: "medium",
    start_date: "2024-02-01",
    end_date: "2024-05-15",
    progress: 40,
    budget: 80000,
    spent_budget: 32000,
    project_manager_id: "2",
    manager_name: "Sarah Manager",
    team_members: ["3"],
    created_at: "2024-01-28",
    updated_at: "2024-03-10",
    created_by: "1",
  },
  {
    id: "p3",
    name: "API Integration Hub",
    description: "Centralized API gateway for third-party integrations",
    status: "on_hold",
    priority: "low",
    start_date: "2024-03-01",
    end_date: "2024-08-30",
    progress: 15,
    budget: 120000,
    spent_budget: 18000,
    project_manager_id: "2",
    manager_name: "Sarah Manager",
    team_members: ["4"],
    created_at: "2024-02-20",
    updated_at: "2024-03-05",
    created_by: "1",
  },
  {
    id: "p4",
    name: "Analytics Dashboard",
    description: "Real-time analytics and reporting dashboard",
    status: "completed",
    priority: "high",
    start_date: "2023-09-01",
    end_date: "2024-01-31",
    progress: 100,
    budget: 95000,
    spent_budget: 91000,
    project_manager_id: "2",
    manager_name: "Sarah Manager",
    team_members: ["3", "4"],
    created_at: "2023-08-25",
    updated_at: "2024-01-31",
    created_by: "1",
  },
  {
    id: "p5",
    name: "CRM System",
    description: "Customer relationship management system",
    status: "in_progress",
    priority: "critical",
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    progress: 25,
    budget: 200000,
    spent_budget: 50000,
    project_manager_id: "2",
    manager_name: "Sarah Manager",
    team_members: ["3", "4"],
    created_at: "2023-12-15",
    updated_at: "2024-03-12",
    created_by: "1",
  },
];
